// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/gofrs/uuid"
	"entgo.io/ent/schema"

	entlocal "github.com/romashorodok/infosec/ent"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User..
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}), field.String("username").Unique(), field.String("password")}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("Participants", Participant.Type),
	}
}
 
func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entlocal.ElkSecurity,
	}
}
