// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"github.com/gofrs/uuid"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User..
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}), field.String("username").Unique(), field.String("password")}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("Participants", Participant.Type),
		// edge.From("Participants", Participant.Type).Ref("users"),


		// // This make role_users many to many
		// edge.From("roles", Role.Type).
		// 	Ref("users"),

		// edge.From("boards", Board.Type).Ref("users"),


		// edge.From("user_roles", Role.Type).Ref("roles"),
		// edge.From("role_users", User.Type).Ref("users"),
		// edge.To("roles", Role.Type),
		// edge.From("role_users", Role.Type).Ref("roles"),
		// edge.To("boards", Board.Type),
		// edge.To("board_users", BoardUsers.Type),
	}
}
