// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"

	"github.com/google/uuid"
	"github.com/romashorodok/infosec/pkg/entutils"
)

// User holds the schema definition for the User entity.
type User struct {
	ent.Schema
}

// Fields of the User..
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.Nil).Default(uuid.New),
		field.String("username").Unique(),
		field.String("password")}
}

func (User) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("participants", Participant.Type),
	}
}

func (User) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entutils.ElkSecurity,
	}
}
