// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Board is the predicate function for board builders.
type Board func(*sql.Selector)

// Grant is the predicate function for grant builders.
type Grant func(*sql.Selector)

// Participant is the predicate function for participant builders.
type Participant func(*sql.Selector)

// Pillar is the predicate function for pillar builders.
type Pillar func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
